const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.join(__dirname, '..');
const sql = fs.readFileSync(path.join(root, 'migrations', '20261002_online_pond.sql'), 'utf8');
const starter = fs.readFileSync(path.join(root, 'migrations', '20261002_online_starter.sql'), 'utf8');
const hardened = fs.readFileSync(path.join(root, 'migrations', '20261002_online_hardening.sql'), 'utf8');
const page = fs.readFileSync(path.join(root, 'online.html'), 'utf8');
const app = fs.readFileSync(path.join(root, 'online-pond.js'), 'utf8');
const config = fs.readFileSync(path.join(root, 'online-config.js'), 'utf8');
const local = fs.readFileSync(path.join(root, 'index.html'), 'utf8');

assert.match(sql, /create table if not exists public\.pwnd_ponds/);
assert.match(sql, /create table if not exists public\.pwnd_buildings/);
assert.match(sql, /references auth\.users\(id\) on delete cascade/);
assert.match(sql, /alter table public\.pwnd_ponds enable row level security/);
assert.match(sql, /alter table public\.pwnd_buildings enable row level security/);
assert.match(sql, /revoke all on public\.pwnd_ponds, public\.pwnd_buildings from anon, authenticated/);
assert.match(sql, /grant execute on function public\.pwnd_get_pond\(\) to authenticated/);
assert.match(sql, /grant execute on function public\.pwnd_pond_action\(text,text,integer,integer,bigint\) to authenticated/);
assert.match(sql, /owner_id uuid := auth\.uid\(\)/);
assert.match(sql, /for update/);
assert.match(sql, /revision_conflict/);
assert.match(sql, /clock_timestamp\(\)/);
assert.match(sql, /least\(28800::numeric/);
assert.match(sql, /pwnd_footprint_distance\(item\.x,item\.y,spring\.x,spring\.y\) <= 2/);
assert.match(sql, /pwnd_footprint_distance\(item\.x,item\.y,spring\.x,spring\.y\) <= 3/);
assert.doesNotMatch(sql, /p_resources|p_user_id|p_client_time|p_reward/i,
  'Only typed actions, never browser resources or time');
assert.match(starter, /alter column water set default 500/);
assert.match(starter, /alter column air set default 300/);
assert.match(hardened, /revoke all on public\.pwnd_ponds, public\.pwnd_buildings from public/);
assert.match(hardened, /alter column carry type numeric\(20,18\)/);
assert.match(hardened, /least\(0\.999999999999999999::numeric/);
assert.match(page, /\/catsdogs\/vendor\/supabase\.js/);
assert.match(page, /\/pwnd\/online-config\.js/);
assert.match(page, /\/pwnd\/online-pond\.js/);
assert.match(page, /lokalen Demo-Spielstand/);
assert.match(local, /href="\/pwnd\/online\.html"/);
assert.match(app, /rpc\('pwnd_get_pond'\)/);
assert.match(app, /rpc\('pwnd_pond_action'/);
assert.match(app, /auth\.signInWithOtp/);
assert.match(app, /auth\.verifyOtp/);
assert.match(app, /requestVersion/);
assert.match(app, /signOut\(\{ scope: 'local' \}\)/);
assert.doesNotMatch(app, /pwnd-profile|localStorage|Date\.now|service.?role/i,
  'Online currency must never read browser saves or client clock');
assert.match(config, /sb_publishable_/);
assert.doesNotMatch(config, /service.?role|sb_secret_/i);
console.log('pwnd online contract tests: ok');
