const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const context = {};
vm.runInNewContext(fs.readFileSync(path.join(__dirname, '..', 'pond-demo.js'), 'utf8'), context);
const P = context.PwndPondDemo;
const plain = value => JSON.parse(JSON.stringify(value));
const initial = { energy: 1000, water: 250, air: 120, love: 60 };
const rich = { ...initial, water: 500, air: 300, love: 100 };
const hour = 3600000;
const start = 1000;

assert.equal(P.GRID_SIZE, 10);
assert.deepEqual(plain(P.SOLAR.cost), { energy: 120, water: 80, air: 20, love: 10 });
assert.deepEqual(plain(P.SPRING.cost), { energy: 80, water: 120, air: 20, love: 10 });
assert.deepEqual(plain(P.REED.cost), { energy: 100, water: 80, air: 120, love: 15 });
assert.deepEqual(Object.values(P.BUILDINGS).map(item => item.perHour), [120, 120, 120]);
assert.equal(P.normalizePondDemo(null, start).buildings.length, 0);
assert.deepEqual(plain(P.normalizePondDemo({ buildings: [{ type: 'solar_lily', x: 4, y: 4 }] }, start).buildings), []);
for (const [x, y] of [[-1, 0], [9, 0], [0, 9], [4, 4], [3, 3], [5, 5]]) {
  assert.equal(P.canPlace([], initial, 'solar_lily', x, y), false, `invalid or core-overlapping origin ${x},${y}`);
}
const first = P.placeBuilding({ buildings: [], resources: rich, type: 'solar_lily', x: 0, y: 0, nowMs: start });
assert.ok(first);
assert.deepEqual(plain(first.resources), { energy: 880, water: 420, air: 280, love: 90 });
assert.deepEqual(rich, { energy: 1000, water: 500, air: 300, love: 100 }, 'a build cannot mutate its caller');
assert.equal(P.placeBuilding({ ...first, type: 'solar_lily', x: 3, y: 0, nowMs: start }), null, 'one producer per type');
assert.equal(P.placeBuilding({ ...first, type: 'spring_pool', x: 1, y: 0, nowMs: start }), null, 'no footprint overlap');
assert.equal(P.placeBuilding({ buildings: [], resources: { ...initial, water: 119 }, type: 'spring_pool', x: 0, y: 0, nowMs: start }), null);
assert.equal(P.placeBuilding({ buildings: [], resources: { ...initial, love: 9 }, type: 'solar_lily', x: 0, y: 0, nowMs: start }), null);
assert.equal(P.footprintDistance({ type: 'solar_lily', x: 0, y: 0 }, { type: 'spring_pool', x: 3, y: 0 }), 2);
assert.equal(P.footprintDistance({ type: 'solar_lily', x: 0, y: 0 }, { type: 'spring_pool', x: 4, y: 0 }), 3);
assert.equal(P.activeBonuses([{ type: 'solar_lily', x: 0, y: 0 }, { type: 'spring_pool', x: 4, y: 0 }]).length, 0);

const spring = P.placeBuilding({ ...first, type: 'spring_pool', x: 2, y: 0, nowMs: start + hour });
assert.equal(spring.buildings[0].bank, 120, 'solar time earned before adjacency is banked at the old rate');
assert.equal(P.productionSummary(spring.buildings, spring.resources, start + hour).pending.energy, 120);
assert.equal(P.productionRates(spring.buildings).solar_lily, 420);
assert.equal(P.activeBonuses(spring.buildings)[0].id, 'sunwater');
const windmill = P.placeBuilding({ ...spring, type: 'reed_windmill', x: 4, y: 0, nowMs: start + 2 * hour });
assert.equal(windmill.buildings[0].bank, 540, 'solar earns 120 before the spring plus 420 after it');
assert.equal(windmill.buildings[1].bank, 120);
assert.deepEqual(plain(P.activeBonuses(windmill.buildings).map(bonus => bonus.id)), ['sunwater', 'reedflow']);
assert.equal(P.productionRates(windmill.buildings).reed_windmill, 240);
const atThree = P.productionSummary(windmill.buildings, windmill.resources, start + 3 * hour);
assert.deepEqual(plain(atThree.pending), { energy: 960, water: 240, air: 240, love: 0 });
const badMove = P.moveBuilding({ ...windmill, type: 'spring_pool', x: 4, y: 4, nowMs: start + 3 * hour });
assert.equal(badMove, null, 'the core stays free during a move');
assert.equal(P.moveBuilding({ ...windmill, type: 'spring_pool', x: 4, y: 0, nowMs: start + 3 * hour }), null, 'moving into the windmill is rejected');
const moved = P.moveBuilding({ ...windmill, type: 'spring_pool', x: 8, y: 8, nowMs: start + 3 * hour });
assert.ok(moved);
assert.equal(Object.hasOwn(moved, 'resources'), false, 'a move cannot spend or grant any resources');
assert.deepEqual(plain(windmill.resources), { energy: 700, water: 220, air: 140, love: 65 });
assert.equal(P.activeBonuses(moved.buildings).length, 0);
assert.equal(moved.buildings[0].bank, 960, 'time before a move retains the old, valid bonus');
const atFour = P.productionSummary(moved.buildings, windmill.resources, start + 4 * hour);
assert.deepEqual(plain(atFour.pending), { energy: 1080, water: 360, air: 360, love: 0 });
const claimed = P.claimProduction({ buildings: moved.buildings, resources: windmill.resources, nowMs: start + 4 * hour });
assert.equal(claimed.resources.energy, windmill.resources.energy + 1080);
assert.equal(claimed.resources.water, windmill.resources.water + 360);
assert.equal(claimed.resources.air, windmill.resources.air + 360);
assert.equal(P.claimProduction({ buildings: claimed.buildings, resources: claimed.resources, nowMs: start + 4 * hour }), null, 'same instant cannot be claimed twice');
const capped = P.productionSummary(first.buildings, { ...first.resources, energy: 1990 }, start + hour);
assert.equal(capped.pending.energy, 10, 'producer collection respects the local cap');
const cappedLater = P.productionSummary(first.buildings, { ...first.resources, energy: 1990 }, start + 2 * hour);
assert.equal(cappedLater.buildings[0].bank, 10, 'excess production is not secretly saved beyond free capacity');
const fullClaim = P.claimProduction({ buildings: first.buildings,
  resources: { ...first.resources, energy: 1990 }, nowMs: start + 2 * hour });
assert.equal(fullClaim.gained.energy, 10);
assert.equal(fullClaim.buildings[0].bank, 0);
assert.equal(P.productionSummary(fullClaim.buildings, { ...first.resources, energy: 1900 }, start + 2 * hour).pending.energy, 0,
  'overflow cannot be claimed retroactively after spending');
assert.equal(P.productionSummary(fullClaim.buildings, { ...first.resources, energy: 1900 }, start + 3 * hour).pending.energy, 100,
  'after spending, fresh production resumes only until the cap');
assert.equal(P.productionSummary(first.buildings, { ...first.resources, energy: 2006 }, start + hour).pending.energy, 0);
assert.equal(P.productionSummary(first.buildings, first.resources, start + 12 * hour).pending.energy, 960, 'at most eight hours offline');
assert.equal(P.productionSummary(first.buildings, first.resources, 500).pending.energy, 0, 'clock rollback earns nothing');
const fractional = P.claimProduction({ buildings: first.buildings, resources: first.resources, nowMs: start + 90_000 });
assert.equal(fractional.gained.energy, 3);
assert.equal(P.productionSummary(fractional.buildings, fractional.resources, start + 120_000).pending.energy, 1, 'fractional time survives a claim');
const old = P.normalizePondDemo({ buildings: [{ type: 'solar_lily', x: 2, y: 3, lastClaimAt: start }], completedAttempts: ['old'] }, start + hour);
assert.equal(old.buildings[0].bank, 0);
assert.equal(P.productionSummary(old.buildings, initial, start + hour).pending.energy, 120, 'old solar saves keep their earned time');
assert.deepEqual(plain(old.completedAttempts), ['old']);
const restored = P.normalizePondDemo({ buildings: windmill.buildings, completedAttempts: ['once'] }, start + 2 * hour);
assert.deepEqual(plain(restored.buildings), plain(windmill.buildings));
assert.deepEqual(plain(restored.completedAttempts), ['once']);

const reward = { energy: 5, water: 47, air: 20, love: 15 };
const awarded = P.settleQuiz({ resources: first.resources, completedAttempts: [], attemptId: 'attempt-one', energyAfter: 885, rewards: reward, answeredCount: 8 });
assert.deepEqual(plain(awarded.resources), { energy: 885, water: 467, air: 300, love: 105 });
assert.equal(P.settleQuiz({ resources: awarded.resources, completedAttempts: awarded.completedAttempts, attemptId: 'attempt-one', energyAfter: 890, rewards: reward, answeredCount: 8 }), null);
assert.equal(P.settleQuiz({ resources: initial, completedAttempts: [], attemptId: 'empty', energyAfter: 1000, rewards: reward, answeredCount: 0 }), null);
assert.equal(P.settleQuiz({ resources: { ...initial, water: Number.MAX_SAFE_INTEGER }, completedAttempts: [], attemptId: 'overflow', energyAfter: 1000, rewards: reward, answeredCount: 8 }), null);
const highQuizEnergy = P.settleQuiz({ resources: { ...initial, energy: 1998 }, completedAttempts: [], attemptId: 'legacy-energy', energyAfter: 2006, rewards: reward, answeredCount: 8 });
assert.equal(highQuizEnergy.resources.energy, 2006, 'quiz energy remains separate from production cap');
console.log('pwnd pond demo tests: ok');
