import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = path.dirname(fileURLToPath(import.meta.url));
const root = path.dirname(dir);
const shell = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const app = fs.readFileSync(path.join(dir, 'index.html'), 'utf8');
const config = JSON.parse(fs.readFileSync(path.join(root, 'vercel.json'), 'utf8'));
const datingApp = fs.readFileSync(path.join(root, 'mycat', 'cats&dogs', 'index.html'), 'utf8');
const datingScript = fs.readFileSync(path.join(root, 'mycat', 'cats&dogs', 'app.js'), 'utf8');
const datingPrivacy = fs.readFileSync(path.join(root, 'mycat', 'cats&dogs', 'privacy.html'), 'utf8');
const datingMigration = fs.readFileSync(path.join(root, 'supabase', 'migrations', '20261004165352_create_mycat_dating_profiles.sql'), 'utf8');
const mycatServiceWorker = fs.readFileSync(path.join(root, 'mycat', 'sw.js'), 'utf8');
const territoryGame = path.join(root, 'TaubenVSKrähen');
const territoryGameHtml = fs.readFileSync(path.join(territoryGame, 'index.html'), 'utf8');
const script = app.match(/<script>([\s\S]*?)<\/script>/)?.[1];

assert.ok(script, 'App-Script fehlt');
assert.match(shell, /5 WEGE/);
assert.match(shell, /fünf erfahrungen · ein ort/);
assert.match(shell, /href="\/pwnd\/"/);
assert.match(shell, /href="\/mydog\/"/);
assert.match(shell, /href="\/mycat\/"/);
assert.doesNotMatch(shell, /href="\/catsdogs\/"/);
assert.match(shell, /href="\/fishroyale\/"/);
assert.match(shell, /03 · PROFIL/);
assert.match(shell, /MyCat/);
assert.match(app, /src="\/catsdogs\/vendor\/supabase\.js"/);
assert.doesNotMatch(app, /src="https:\/\/cdn\.jsdelivr\.net/);
assert.match(script, /myDogLaunch=testParams.get\('from'\)==='mydog',testMode=!myDogLaunch\|\|testParams.get\('test'\)==='1'/);
assert.match(script, /MYDOG_HANDOFF_KEY='manualai_mydog_handoff_v1'/);
assert.match(script, /version!==1/);
assert.match(script, /U.importedB5/);
assert.match(script, /single-use|30\*60\*1000/);
assert.match(script, /U=testQuick\?/);
assert.match(script, /function gender\(\)/);
assert.match(script, /Diese Angabe bestimmt, wen du kennenlernen kannst\./);
assert.doesNotMatch(script, /Wähle, was sich für dich richtig anfühlt/);
assert.doesNotMatch(script, /function orientation\(\)|data-o=|homo|gleiches Geschlecht|Dating-Präferenz/);
assert.match(script, /U\.g=b\.dataset\.g;U\.o='hetero';if\(U\.importedB5\)/);
assert.match(script, /orientation:'hetero'/);
assert.match(script, /function quiz\(i,a\)/);
assert.match(script, /<h3>Wie alt bist du\?<\/h3><p id="agePreview"/);
assert.match(script, /\$\{petYears\(v,m\.an\)\} \$\{m\.an=='dog'\?'Hundejahre':'Katzenjahre'\}/);
assert.doesNotMatch(script, /\?petAgeText\(v,m\.an\)/);
assert.doesNotMatch(script, /Du siehst dein echtes Alter mit Tierjahren/);
assert.match(script, /a\.textContent=\(S\.ageBands&&S\.ageBands\[oid\]\)\|\|AG\[ageGroup\(Number\(o\.age\)\)\]/);
assert.doesNotMatch(script, /Altersspanne des Gegenübers:/);
assert.match(script, /rpc\('submit_cats_dogs_feedback'/);
assert.match(script, /ba=testMode\?\(U\.an=='dog'\?'cat':'dog'\)/);
assert.ok(fs.statSync(path.join(dir, 'vendor', 'supabase.js')).size > 150000);
assert.ok(fs.statSync(path.join(dir, 'vendor', 'LICENSE')).size > 500);
assert.ok(config.redirects.some(r => r.source === '/catsdogs' && r.destination === '/catsdogs/'));
assert.ok(config.rewrites.some(r => r.source === '/catsdogs' && r.destination === '/catsdogs/index.html'));
assert.ok(config.redirects.some(r => r.source === '/mycat' && r.destination === '/mycat/'));
assert.ok(config.rewrites.some(r => r.source === '/mycat' && r.destination === '/mycat/index.html'));
assert.ok(config.redirects.some(r => r.source === '/mycat/cats&dogs' && r.destination === '/mycat/cats&dogs/'));
assert.ok(config.rewrites.some(r => r.source === '/mycat/cats&dogs' && r.destination === '/mycat/cats&dogs/index.html'));
assert.match(datingApp, /<title>MyCat × MyDog – Dating-Profil<\/title>/);
assert.match(datingApp, /app\.js\?v=20261004-profile-v1/);
assert.doesNotMatch(datingApp, /In Vorbereitung/);
assert.match(datingScript, /const GENOTYPES = \['XX', 'XY', 'X0', 'XXY', 'XYY', 'XXX'\]/);
assert.match(datingScript, /mycat_dating_profiles/);
assert.match(datingScript, /genotype_consent_version/);
assert.match(datingScript, /Do not upload raw questionnaire answers/);
assert.doesNotMatch(datingScript, /cats_dogs_profiles|gender:/);
assert.match(datingScript, /Partnersuche bleibt aus, bis die Matching-Regeln festgelegt sind/);
assert.match(datingMigration, /genotype in \('XX', 'XY', 'X0', 'XXY', 'XYY', 'XXX'\)/);
assert.match(datingMigration, /enable row level security/);
assert.match(datingMigration, /auth\.uid\(\) = user_id/);
assert.match(datingPrivacy, /nicht für Matches, Rankings oder andere Entscheidungen verwendet/);
assert.match(mycatServiceWorker, /'\/mycat\/cats&dogs\/index\.html'/);
assert.match(mycatServiceWorker, /'\/mycat\/cats&dogs\/app\.js'/);
assert.match(mycatServiceWorker, /'\/mycat\/cats&dogs\/privacy\.html'/);
assert.ok(config.redirects.some(r => r.source === '/fishroyale' && r.destination === '/fishroyale/'));
assert.ok(config.rewrites.some(r => r.source === '/fishroyale' && r.destination === '/fishroyale/index.html'));
assert.match(shell, /href="\/TaubenVSKrähen\/"/);
assert.match(shell, /<h3>pidgeons &amp; crows<\/h3>/);
assert.ok(config.redirects.some(r => r.source === '/TaubenVSKrähen' && r.destination === '/TaubenVSKrähen/'));
assert.ok(config.rewrites.some(r => r.source === '/TaubenVSKrähen' && r.destination === '/TaubenVSKrähen/index.html'));
assert.ok(config.headers.some(h => h.headers.some(v => v.key === 'Content-Security-Policy' && v.value.includes("'wasm-unsafe-eval'"))));
assert.match(territoryGameHtml, /<title>pidgeons (?:&amp;|&) crows<\/title>/);
assert.match(territoryGameHtml, /lang="de-DE"/);
assert.ok(fs.statSync(path.join(territoryGame, 'index.pck')).size > 1_000_000);
assert.ok(fs.statSync(path.join(territoryGame, 'index.wasm')).size > 1_000_000);
assert.ok(fs.statSync(path.join(territoryGame, 'favicon.png')).size > 1_000);
assert.ok(config.headers.some(h => h.headers.some(v => v.key === 'Content-Security-Policy' && v.value.includes("script-src 'self'"))));
console.log('manualAI deployment smoke passed: five app cards, Godot export, routes, CSP and vendored browser library.');
