import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = path.dirname(fileURLToPath(import.meta.url));
const root = path.dirname(dir);
const shell = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const app = fs.readFileSync(path.join(dir, 'index.html'), 'utf8');
const config = JSON.parse(fs.readFileSync(path.join(root, 'vercel.json'), 'utf8'));
const continuation = fs.readFileSync(path.join(root, 'mycat', 'cats&dogs', 'index.html'), 'utf8');
const mycatServiceWorker = fs.readFileSync(path.join(root, 'mycat', 'sw.js'), 'utf8');
const script = app.match(/<script>([\s\S]*?)<\/script>/)?.[1];

assert.ok(script, 'App-Script fehlt');
assert.match(shell, /4 WEGE/);
assert.match(shell, /href="\/pwnd\/"/);
assert.match(shell, /href="\/mydog\/"/);
assert.match(shell, /href="\/mycat\/"/);
assert.doesNotMatch(shell, /href="\/catsdogs\/"/);
assert.match(shell, /href="\/fishroyale\/"/);
assert.match(shell, /03 · PROFIL/);
assert.match(shell, /MyCat/);
assert.match(app, /src="\/catsdogs\/vendor\/supabase\.js"/);
assert.doesNotMatch(app, /src="https:\/\/cdn\.jsdelivr\.net/);
assert.match(script, /testMode=true,testQuick=/);
assert.match(script, /U=testQuick\?/);
assert.match(script, /function gender\(\)/);
assert.match(script, /Diese Angabe bestimmt, wen du kennenlernen kannst\./);
assert.doesNotMatch(script, /Wähle, was sich für dich richtig anfühlt/);
assert.doesNotMatch(script, /function orientation\(\)|data-o=|homo|gleiches Geschlecht|Dating-Präferenz/);
assert.match(script, /U\.g=b\.dataset\.g;U\.o='hetero';quiz\(0,\[\]\)/);
assert.match(script, /orientation:'hetero'/);
assert.match(script, /function quiz\(i,a\)/);
assert.match(script, /<h3>Wie alt bist du\?<\/h3><p id="agePreview"/);
assert.match(script, /\$\{petYears\(v,m\.an\)\} \$\{m\.an=='dog'\?'Hundejahre':'Katzenjahre'\}/);
assert.doesNotMatch(script, /\?petAgeText\(v,m\.an\)/);
assert.doesNotMatch(script, /Du siehst dein echtes Alter mit Tierjahren/);
assert.match(script, /a\.textContent=\(S\.ageBands&&S\.ageBands\[oid\]\)\|\|AG\[ageGroup\(Number\(o\.age\)\)\]/);
assert.doesNotMatch(script, /Altersspanne des Gegenübers:/);
assert.match(script, /rpc\('submit_cats_dogs_feedback'/);
assert.match(script, /ba=testMode\?\(U\.an=='dog'\?'cat':'dog'\)/);
assert.ok(fs.statSync(path.join(dir, 'vendor', 'supabase.js')).size > 150000);
assert.ok(fs.statSync(path.join(dir, 'vendor', 'LICENSE')).size > 500);
assert.ok(config.redirects.some(r => r.source === '/catsdogs' && r.destination === '/catsdogs/'));
assert.ok(config.rewrites.some(r => r.source === '/catsdogs' && r.destination === '/catsdogs/index.html'));
assert.ok(config.redirects.some(r => r.source === '/mycat' && r.destination === '/mycat/'));
assert.ok(config.rewrites.some(r => r.source === '/mycat' && r.destination === '/mycat/index.html'));
assert.ok(config.redirects.some(r => r.source === '/mycat/cats&dogs' && r.destination === '/mycat/cats&dogs/'));
assert.ok(config.rewrites.some(r => r.source === '/mycat/cats&dogs' && r.destination === '/mycat/cats&dogs/index.html'));
assert.match(continuation, /Oder suchst du eigentlich nach Liebe\?/);
assert.match(continuation, /Die MyCat-Ergebnisse werden noch nicht an eine Dating-App übergeben\./);
assert.match(mycatServiceWorker, /'\/mycat\/cats&dogs\/index\.html'/);
assert.ok(config.redirects.some(r => r.source === '/fishroyale' && r.destination === '/fishroyale/'));
assert.ok(config.rewrites.some(r => r.source === '/fishroyale' && r.destination === '/fishroyale/index.html'));
assert.ok(config.headers.some(h => h.headers.some(v => v.key === 'Content-Security-Policy' && v.value.includes("script-src 'self'"))));
console.log('cats&dogs deployment smoke passed: app cards, test-only flow, routes, CSP and vendored browser library.');
