const $ = (id) => document.getElementById(id);
const screens = [...document.querySelectorAll('.screen')];
const TYPE_NAMES = { recall: 'RAPID RECALL', pattern: 'PATTERN RECOGNITION', causal: 'CAUSAL CHOICE', logic: 'LOGIC TRAP', source: 'SOURCE SENSE', risk: 'AGENT DECISION' };
const SKILL_NAMES = { recall: 'Abruf', pattern: 'Muster', causal: 'Kausalität', logic: 'Logik', source: 'Quellengefühl', risk: 'Risiko' };
const RANKS = [{ min: 0, name: 'UNAWAKENED' }, { min: 800, name: 'INITIATE' }, { min: 1000, name: 'THINKER' }, { min: 1200, name: 'STRATEGIST' }, { min: 1400, name: 'ARCHITECT' }, { min: 1600, name: 'INTELLIGENCE' }];
const UPGRADES = [
  { id: 'memory', name: 'MEMORY BUFFER', text: '+2 Sekunden bei Rapid-Recall-Fragen.', apply: s => { s.mods.time = 2000; } },
  { id: 'causal', name: 'CAUSAL LENS', text: 'Kausalitätsfragen verursachen 15 % weniger Schaden bei Fehlern.', apply: s => { s.mods.causalShield = .15; } },
  { id: 'risk', name: 'RISK PROTOCOL', text: '+25 % Schaden bei schwierigen Fragen — aber +20 % Selbstschaden bei Fehlern.', apply: s => { s.mods.risk = .25; s.mods.riskPenalty = .2; } },
  { id: 'calm', name: 'CALM CORE', text: 'Eine falsche Antwort pro Match verliert nur einen Combo-Punkt.', apply: s => { s.mods.calm = true; } },
  { id: 'scanner', name: 'PATTERN SCANNER', text: 'Einmal pro Match eine Antwortoption entfernen.', apply: s => { s.mods.scanner = true; } },
];
const QUESTIONS = [
  { id:'r1', type:'recall', skill:'recall', difficulty:.25, time:10000, prompt:'Welcher Planet ist der Sonne am nächsten?', options:['Venus','Mars','Merkur','Jupiter'], answer:2, explanation:'Merkur ist der sonnennächste Planet.' },
  { id:'r2', type:'recall', skill:'recall', difficulty:.45, time:11000, prompt:'Wie viele Seiten hat ein Hexagon?', options:['5','6','7','8'], answer:1, explanation:'Ein Hexagon ist ein Sechseck.' },
  { id:'r3', type:'recall', skill:'recall', difficulty:.65, time:13000, prompt:'Welches Gas macht den größten Anteil der Erdatmosphäre aus?', options:['Sauerstoff','Stickstoff','Kohlendioxid','Wasserstoff'], answer:1, explanation:'Stickstoff macht ungefähr 78 % der Erdatmosphäre aus.' },
  { id:'p1', type:'pattern', skill:'pattern', difficulty:.35, time:18000, prompt:'Welche Zahl setzt die Reihe sinnvoll fort? 2, 4, 8, 16, …', options:['20','24','30','32'], answer:3, explanation:'Jede Zahl wird mit 2 multipliziert.' },
  { id:'p2', type:'pattern', skill:'pattern', difficulty:.58, time:22000, prompt:'Welche Form folgt logisch? Kreis, Dreieck, Kreis, Dreieck, …', options:['Kreis','Quadrat','Dreieck','Linie'], answer:0, explanation:'Das Muster wechselt abwechselnd zwischen Kreis und Dreieck.' },
  { id:'p3', type:'pattern', skill:'pattern', difficulty:.72, time:26000, prompt:'Was folgt? 1, 1, 2, 3, 5, 8, …', options:['11','12','13','15'], answer:2, explanation:'Jede Zahl entsteht aus der Summe der beiden vorherigen Zahlen.' },
  { id:'c1', type:'causal', skill:'causal', difficulty:.42, time:26000, prompt:'Eine Stadt erhöht die Parkgebühren stark. Was ist — unter gleichen Bedingungen — am wahrscheinlichsten?', options:['Alle Autos verschwinden sofort.','Ein Teil der Menschen wechselt auf Alternativen.','Die Straßen werden automatisch breiter.','Der öffentliche Verkehr wird kostenlos.'], answer:1, explanation:'Ein höherer Preis kann die Nachfrage nach Parkplätzen senken und Alternativen attraktiver machen. Die Folge ist wahrscheinlich, aber nicht zwingend.' },
  { id:'c2', type:'causal', skill:'causal', difficulty:.62, time:30000, prompt:'Eine Pflanze erhält mehr Licht, aber weiterhin kaum Wasser. Welche Aussage ist am saubersten?', options:['Mehr Licht garantiert gesundes Wachstum.','Mehr Licht kann helfen, wenn Wasser nicht zum limitierenden Faktor wird.','Wasser spielt für Pflanzen keine Rolle.','Die Pflanze wächst immer doppelt so schnell.'], answer:1, explanation:'Ein Faktor wirkt nur, wenn andere notwendige Bedingungen ausreichend vorhanden sind.' },
  { id:'c3', type:'causal', skill:'causal', difficulty:.78, time:35000, prompt:'Ein Team arbeitet länger, macht aber mehr Fehler. Welche Erklärung ist am plausibelsten?', options:['Arbeitszeit verursacht immer Fehler.','Müdigkeit könnte die Genauigkeit senken; weitere Daten wären sinnvoll.','Mehr Arbeit verbessert immer die Qualität.','Fehler beweisen, dass das Team unfähig ist.'], answer:1, explanation:'Die Aussage nennt eine plausible Kausalhypothese, verwechselt sie aber nicht mit einem Beweis.' },
  { id:'l1', type:'logic', skill:'logic', difficulty:.45, time:30000, prompt:'Alle Noren sind blau. Einige blaue Dinge sind schwer. Was folgt zwingend?', options:['Einige Noren sind schwer.','Alle Noren sind schwer.','Es folgt nichts über das Gewicht der Noren.','Keine Noren sind schwer.'], answer:2, explanation:'Aus „einige blaue Dinge sind schwer“ folgt nicht, dass diese Dinge Noren sind.' },
  { id:'l2', type:'logic', skill:'logic', difficulty:.62, time:34000, prompt:'Wenn es regnet, wird der Boden nass. Der Boden ist nass. Was folgt zwingend?', options:['Es hat geregnet.','Es hat nicht geregnet.','Nichts Sicheres über die Ursache des nassen Bodens.','Der Regen war stark.'], answer:2, explanation:'Der Boden kann auch aus anderen Gründen nass sein. Das wäre ein unzulässiger Umkehrschluss.' },
  { id:'l3', type:'logic', skill:'logic', difficulty:.78, time:40000, prompt:'Kein guter Plan ist völlig risikofrei. Plan X ist risikofrei. Was folgt?', options:['Plan X ist ein guter Plan.','Plan X ist kein guter Plan.','Plan X ist unmöglich.','Man kann nichts schließen.'], answer:1, explanation:'Wenn kein guter Plan risikofrei ist, kann ein risikofreier Plan nicht gut sein.' },
  { id:'s1', type:'source', skill:'source', difficulty:.4, time:24000, prompt:'Welche Aussage ist am belastbarsten formuliert?', options:['Das beweist endgültig, dass …','Die Daten legen nahe, dass …, mit diesen Einschränkungen.','Jeder weiß, dass …','Eine Person im Internet sagt …'], answer:1, explanation:'Gute Aussagen trennen Daten, Schlussfolgerung und Einschränkungen.' },
  { id:'s2', type:'source', skill:'source', difficulty:.6, time:28000, prompt:'Du liest eine überraschende Behauptung. Was ist der beste erste Schritt?', options:['Sie sofort weiterleiten.','Nur die Überschrift bewerten.','Quelle, Belege und Gegenpositionen prüfen.','Sie ablehnen, weil sie überraschend ist.'], answer:2, explanation:'Eine ungewöhnliche Behauptung braucht nicht automatisch Ablehnung, aber eine sorgfältige Prüfung.' },
  { id:'s3', type:'source', skill:'source', difficulty:.76, time:32000, prompt:'Was macht eine Quelle für eine konkrete Tatsachenfrage besonders nützlich?', options:['Sie klingt selbstbewusst.','Sie nennt überprüfbare Methode, Daten und Kontext.','Sie hat viele Emojis.','Sie bestätigt deine Meinung.'], answer:1, explanation:'Nachvollziehbarkeit und Kontext sind stärker als Tonfall oder Bestätigung.' },
  { id:'risk1', type:'risk', skill:'risk', difficulty:.55, time:12000, prompt:'Du liegst knapp zurück. Welche Entscheidung passt zu einem kontrollierten Comeback?', options:['Sichere Frage: wenig Schaden, hohe Trefferchance.','Riskante Frage: hohe Belohnung, aber hoher Verlust bei Fehler.','Sofort aufgeben.','Zufällig klicken.'], answer:1, explanation:'Ein kontrolliertes Comeback akzeptiert Risiko bewusst und macht die Konsequenz sichtbar.' },
  { id:'risk2', type:'risk', skill:'risk', difficulty:.7, time:12000, prompt:'Die AI greift wiederholt deine Logikschwäche an. Was ist die intelligenteste Vorbereitung?', options:['Nur noch schnelle Fakten raten.','Ein Upgrade wählen, das Fehlerfolgen begrenzt.','Die Schwäche ignorieren.','Die Zeit immer weiter verkürzen.'], answer:1, explanation:'Die eigene Schwäche zu erkennen und ihre Konsequenzen zu begrenzen ist eine strategische Reaktion.' },
];

const saved = JSON.parse(localStorage.getItem('pwnd-profile') || 'null');
const state = { ip: saved?.ip ?? 1000, calibration: saved?.calibration ?? 0, upgrades: saved?.upgrades ?? [], mods: {}, match: null, timerId: null, sound: false };
const esc = (s) => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rank = ip => [...RANKS].reverse().find(r => ip >= r.min) || RANKS[0];
function save(){ localStorage.setItem('pwnd-profile', JSON.stringify({ ip: Math.round(state.ip), calibration: state.calibration, upgrades: state.upgrades })); }
function show(id){ screens.forEach(s => s.classList.toggle('active', s.id === id)); window.scrollTo(0,0); }
function formatTime(ms){ return `${String(Math.ceil(ms/1000)).padStart(2,'0')}`; }
function weightedQuestion(){
  const m = state.match; const recent = m.history.slice(-2).map(x => x.question.id); const weak = Object.entries(m.skills).sort((a,b)=>a[1]-b[1])[0][0];
  let candidates = QUESTIONS.filter(q => !recent.includes(q.id) && (m.round < 2 || q.skill === weak || q.type !== m.history.at(-1)?.question.type));
  if (!candidates.length) candidates = QUESTIONS.filter(q => !recent.includes(q.id));
  const target = Math.min(.9, .25 + (m.round / 10) * .55 + (m.accuracy < .5 ? -.1 : 0));
  return candidates.sort((a,b)=>Math.abs(a.difficulty-target)-Math.abs(b.difficulty-target))[0];
}
function startMatch(){
  state.mods = {}; state.upgrades.forEach(id => UPGRADES.find(u=>u.id===id)?.apply(state));
  state.match = { round:0, total:10, playerHp:100, aiHp:100, combo:0, history:[], skills:{recall:.5,pattern:.5,causal:.5,logic:.5,source:.5,risk:.5}, accuracy:0, opponent:'MIRROR', selected:null, current:null };
  $('roundTotal').textContent = state.match.total; $('opponentLabel').textContent = 'MIRROR'; $('phaseLabel').textContent = state.calibration < 1 ? 'CALIBRATION' : 'RANKED DEMO'; show('screenBattle'); nextQuestion();
}
function nextQuestion(){
  const m=state.match; if(m.round >= m.total) return finishMatch(); m.round++; m.current=weightedQuestion(); m.selected=null; m.submitted=false; renderBattle(); startTimer(m.current.time + (state.mods.time || 0));
}
function renderBattle(){
  const m=state.match, q=m.current; $('roundNo').textContent=m.round; $('questionType').textContent=TYPE_NAMES[q.type]; $('questionTitle').textContent=q.prompt; $('questionHint').textContent=q.type==='risk'?'Deine Entscheidung hat Konsequenzen.':'Wähle eine Antwort.'; $('comboText').textContent=`COMBO ${m.combo}`; $('skillProfile').textContent=`${SKILL_NAMES[weakest(m.skills)]} wird beobachtet`;
  $('playerHealth').style.width=`${Math.max(0,m.playerHp)}%`; $('aiHealth').style.width=`${Math.max(0,m.aiHp)}%`; $('playerHpText').textContent=Math.ceil(m.playerHp); $('aiHpText').textContent=Math.ceil(m.aiHp); $('lockBtn').disabled=true;
  $('answers').innerHTML=q.options.map((o,i)=>`<button class="answer" type="button" data-answer="${i}"><span class="answer-index">${String.fromCharCode(65+i)}</span><span>${esc(o)}</span></button>`).join('');
  document.querySelectorAll('.answer').forEach(btn=>btn.addEventListener('click',()=>selectAnswer(Number(btn.dataset.answer)))); $('aiComment').textContent = m.round===1 ? 'MIRROR beobachtet deine erste Entscheidung.' : adaptiveComment(m);
}
function weakest(skills){ return Object.entries(skills).sort((a,b)=>a[1]-b[1])[0][0]; }
function adaptiveComment(m){ const w=SKILL_NAMES[weakest(m.skills)]; if(m.combo>=2) return 'Interessant. Deine Sicherheit steigt — also wechsle ich die Perspektive.'; if(m.history.at(-1)?.correct===false) return `Deine ${w}-Lücke ist sichtbar. Ich stelle die nächste Frage nicht zufällig.`; return 'Noch kein klares Muster. Eine weitere Entscheidung genügt.'; }
function startTimer(limit){ clearInterval(state.timerId); const started=performance.now(); const tick=()=>{ const left=Math.max(0,limit-(performance.now()-started)); $('timer').textContent=`00:${formatTime(left)}`; $('timer').classList.toggle('danger',left<5000); if(left<=0){clearInterval(state.timerId); if(!state.match.submitted) submitAnswer(state.match.selected ?? -1,limit);} }; tick(); state.timerId=setInterval(tick,100); state.match.startedAt=started; }
function selectAnswer(index){ if(state.match.submitted) return; state.match.selected=index; $('lockBtn').disabled=false; document.querySelectorAll('.answer').forEach(b=>b.classList.toggle('selected',Number(b.dataset.answer)===index)); }
function submitAnswer(index, forcedMs=null){
  const m=state.match,q=m.current; if(m.submitted) return; m.submitted=true; m.selected=index; clearInterval(state.timerId); const time=forcedMs ?? Math.max(1,performance.now()-m.startedAt); const correct=index===q.answer; const ratio=Math.min(1,time/q.time); const speed=.75+(1-ratio)*.75; let damage=correct?Math.round(10*speed*(1+m.combo*.08)):0; if(correct && q.difficulty>.65) damage=Math.round(damage*(1+(state.mods.risk||0))); let selfDamage=correct?0:Math.round(5+q.difficulty*7); if(!correct && q.type==='causal') selfDamage=Math.round(selfDamage*(1-(state.mods.causalShield||0))); if(!correct && state.mods.riskPenalty) selfDamage=Math.round(selfDamage*(1+state.mods.riskPenalty)); if(!correct && state.mods.calm && m.combo>0) m.combo=Math.max(0,m.combo-1); else if(!correct) m.combo=0; if(correct)m.combo++; m.aiHp=Math.max(0,m.aiHp-damage); m.playerHp=Math.max(0,m.playerHp-selfDamage); m.skills[q.skill]=Math.max(0,Math.min(1,m.skills[q.skill]+(correct?.09:-.12))); m.history.push({question:q,correct,time,damage,selfDamage}); m.accuracy=m.history.filter(x=>x.correct).length/m.history.length;
  document.querySelectorAll('.answer').forEach((b,i)=>{b.disabled=true;if(i===q.answer)b.classList.add('correct');if(i===index&&i!==q.answer)b.classList.add('wrong')}); $('lockBtn').disabled=true; showRoundResult({correct,time,damage,selfDamage,q});
}
function showRoundResult(r){ $('resultOrbit').classList.toggle('miss',!r.correct); $('resultOrbit').textContent=r.correct?'+' :'×'; $('roundEyebrow').textContent=r.correct?'DIRECT HIT':'AI COUNTERATTACK'; $('roundTitle').textContent=r.correct?'Treffer bestätigt.':'Die AI hat gekontert.'; $('roundCopy').textContent=r.correct?`Du hast ${r.damage} Schaden verursacht${r.time<r.q.time*.45?' — schnell und präzise.':'.'}`:`Du hast die Frage verfehlt und ${r.selfDamage} Schaden genommen. Die Konsequenz bleibt bestehen.`; $('resultTime').textContent=`${(r.time/1000).toFixed(1)} s`; $('resultDamage').textContent=r.correct?`+${r.damage}`:`-${r.selfDamage}`; $('resultAccuracy').textContent=r.correct?'KORREKT':'FEHLER'; $('explanation').textContent=r.q.explanation; $('continueBtn').textContent=state.match.round>=state.match.total?'Match auswerten →':'Nächste Runde →'; show('screenRound'); }
function finishMatch(){
  const m=state.match, before=state.ip; const outcome=m.aiHp<=m.playerHp?1:0; const expected=1/(1+Math.pow(10,((1000-before)/400))); const score=.5*outcome+.25*m.accuracy+.15*(m.history.reduce((a,x)=>a+x.question.difficulty,0)/m.history.length)+.1*Math.min(1,m.history.filter(x=>x.correct&&x.time<x.question.time*.55).length/3); const k=state.calibration<1?48:24; const delta=Math.round(k*(score-expected)); state.ip=Math.max(0,Math.round(before+delta)); state.calibration=Math.min(1,state.calibration+1); save(); const skillValues=m.skills; const strongest=Object.entries(skillValues).sort((a,b)=>b[1]-a[1])[0][0], weak=Object.entries(skillValues).sort((a,b)=>a[1]-b[1])[0][0]; $('endResult').textContent=outcome?'WIN':'LOSS'; $('endResult').style.color=outcome?'var(--cyan)':'var(--pink)'; $('ipChange').textContent=`${delta>=0?'+':''}${delta} IP`; $('endTitle').textContent=outcome?'Die AI wurde gelesen.':'Die AI hat dein Muster gelesen.'; $('endCopy').textContent=`${m.history.filter(x=>x.correct).length}/${m.total} Antworten korrekt. IP misst hier deine Duellleistung — nicht die Anzahl deiner gespielten Runden.`; $('ipValue').textContent=state.ip; $('rankValue').textContent=rank(state.ip).name; $('strengthValue').textContent=SKILL_NAMES[strongest]; $('weaknessValue').textContent=SKILL_NAMES[weak]; renderUpgrades(); show('screenEnd'); }
function renderUpgrades(){ const choices=[...UPGRADES].sort(()=>Math.random()-.5).slice(0,3); $('upgrades').innerHTML=choices.map(u=>`<label class="upgrade"><input type="radio" name="upgrade" value="${u.id}"><strong>${u.name}</strong><small>${u.text}</small></label>`).join(''); document.querySelectorAll('.upgrade').forEach(x=>x.addEventListener('click',()=>{document.querySelectorAll('.upgrade').forEach(y=>y.classList.remove('selected'));x.classList.add('selected'); const id=x.querySelector('input').value;if(!state.upgrades.includes(id))state.upgrades=[...state.upgrades.slice(-2),id];save();})); }
$('startBtn').addEventListener('click',startMatch); $('lockBtn').addEventListener('click',()=>submitAnswer(state.match.selected)); $('continueBtn').addEventListener('click',()=>state.match.round>=state.match.total?finishMatch():(show('screenBattle'),nextQuestion())); $('againBtn').addEventListener('click',startMatch); $('soundToggle').addEventListener('click',()=>{state.sound=!state.sound;$('soundToggle').textContent=state.sound?'◉':'♪';});
